{
 "title": "MY_BORD",
 "time": { "from": "2021-10-28T05:58:29.653Z", "to": "2021-10-28T11:58:29.653Z" },
 "panels": [
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "collectdubuntu-bionic.interface-enp0s3.if_packets.*"
    }
   ]
  },
  {
   "title": "LOAD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdubuntu-bionic.load.load.*"
    }
   ]
  },
  {
   "title": "df_free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdubuntu-bionic.df-root.df_complex-free"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdubuntu-bionic.memory.memory-used"
    }
   ]
  },
  {
   "title": "df_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdubuntu-bionic.df-root.df_complex-used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectdubuntu-bionic.cpu-0.cpu-system"
    }
   ]
  }
 ]
}